// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".

import { compositePreset } from '@arroyodev-llc/utils.unbuild-composite-preset'
import { defineBuildConfig } from 'unbuild'

export default defineBuildConfig({
	name: 'construct.awscdk.cloudfront-url-rewrite',
	declaration: false,
	clean: true,
	entries: [
		'./src/index',
		{
			input: './src/index',
			declaration: true,
		},
		{
			input: './src/handler.function',
			declaration: false,
		},
	],
	sourcemap: true,
	rollup: {
		emitCJS: true,
		cjsBridge: true,
		esbuild: {
			treeShaking: true,
			sourcemap: true,
		},
	},
	preset: compositePreset(),
	failOnWarn: false,
})
